version: 0.2

phases:
  build:
    commands:
      - ./gradlew assemble
artifacts:
  files:
    - app/build/outputs/apk/release/app-release-unsigned.apk
    - app/build/outputs/apk/debug/app-debug.apk 
